endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

management:
  context-path: /actuator
  security:
    enabled: false

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
security:
  user:
    name: actuator
    password: actuator1@3$

spring:
  data:
    mongodb:
      host: 101.200.43.126
      database: uaa
      authentication-database: admin
      port: 27017
      username: mongo-user
      password: mongo@sec
  datasource:
    url: jdbc:mysql://localhost:3306/uaa?characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxActive: 1000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  redis:
    timeout: 10000
    database: 0
    host: 101.200.43.126
    port: 6379
#    password: jkgj
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0