management:
  security:
    enabled: false

spring:
  data:
    mongodb:
      database: uaa
  datasource:
    url: jdbc:mysql://${spring.datasource.host}/uaa?characterEncoding=utf8&useUnicode=true&useSSL=false