spring:
  cloud:
    config:
      server:
        git:
          uri: ${git.url}
          username: ${git.username}
          password: ${git.password}
        native:
          search-locations: "file:${config.resources}"